# Generated by Django 2.2.7 on 2019-11-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_auto_20191115_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
