# Generated by Django 2.2.7 on 2019-11-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_auto_20191115_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='contactno',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='email',
            field=models.EmailField(max_length=45),
        ),
    ]
